jobs:
  - job: Linux
    pool:
      vmImage: 'ubuntu-16.04'

    strategy:
      matrix:
        CI:
          TESTS: ci
        ITS-LTS:
          TESTS: it
          SQ_VERSION: LATEST_RELEASE[6.7]
        ITS-LATEST:
          TESTS: it
          SQ_VERSION: LATEST_RELEASE
        ITS-NEXT:
          TESTS: it
          SQ_VERSION: DEV

    steps:
      - script: |
          ./ci.sh
        displayName: 'Build with Maven'
        env:
          DEPLOY_USERNAME: $(DEPLOY_USERNAME)
          DEPLOY_PASSWORD: $(DEPLOY_PASSWORD)
          BINTRAY_DEPLOY_PASSWORD: $(BINTRAY_DEPLOY_PASSWORD)
          BINTRAY_DEPLOY_USERNAME: $(BINTRAY_DEPLOY_USERNAME)


  - job: Windows
    pool:
      vmImage: 'vs2017-win2016'

    steps:
      - task: SonarQubePrepare@4
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
        inputs:
          SonarQube: 'SonarQube'
          scannerMode: 'Other'

      - task: Maven@3
        inputs:
          goals: 'org.jacoco:jacoco-maven-plugin:prepare-agent package org.jacoco:jacoco-maven-plugin:report org.jacoco:jacoco-maven-plugin:report-aggregate'
          jdkVersionOption: 1.11
          sonarQubeRunAnalysis: true

      - task: CopyFiles@2
        displayName: 'Copy artifact: sonar-plsql-open-plugin'
        inputs:
          sourceFolder: '$(system.defaultworkingdirectory)'
          contents: 'sonar-plsql-open-plugin/target/sonar-plsql-open-plugin*.jar'
          targetFolder: '$(build.artifactstagingdirectory)/plugin'
          flattenFolders: true

      - task: CopyFiles@2
        displayName: 'Copy artifact: zpa-toolkit'
        inputs:
          sourceFolder: '$(system.defaultworkingdirectory)'
          contents: 'zpa-toolkit/target/zpa-toolkit*.jar'
          targetFolder: '$(build.artifactstagingdirectory)/toolkit'
          flattenFolders: true

      - task: PublishBuildArtifacts@1
        displayName: 'Publish artifact: sonar-plsql-open-plugin'
        inputs:
          artifactName: 'sonar-plsql-open-plugin'
          pathtoPublish: '$(build.artifactstagingdirectory)/plugin'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish artifact: sonar-plsql-open-plugin'
        inputs:
          artifactName: 'zpa-toolkit'
          pathtoPublish: '$(build.artifactstagingdirectory)/toolkit'

      - task: PublishCodeCoverageResults@1
        inputs:
          summaryFileLocation: '$(System.DefaultWorkingDirectory)/report-aggregate/target/site/jacoco-aggregate/jacoco.xml'
          reportDirectory: '$(System.DefaultWorkingDirectory)/report-aggregate/target/site/jacoco-aggregate'
